version: '3.2'

services:
  filebeat:
    build:
      context: .
    networks:
      - testnet
    depends_on:
      - test_server
  test_server:
    build:
      context: test-server
    ports:
      - 8888:8888
    networks:
      - testnet

networks:
  testnet:
    driver: bridge
